# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: "cli"
    env:
      - CGO_ENABLED=0
    main: ./cmd/start_server/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: start_server
archives:
  - builds:
      - "cli"
    name_template: "start_server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
