# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: "cli-amd64"
    env:
      - CGO_ENABLED=0
    main: ./cmd/start_server/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    binary: start_server
    ldflags:
      - -s -w
      - -X github.com/shogo82148/server-starter.version={{.Version}}
      - -X github.com/shogo82148/server-starter.commit={{.ShortCommit}}
  - id: "cli-arm64"
    env:
      - CGO_ENABLED=0
    main: ./cmd/start_server/main.go
    goos:
      - linux
      - darwin
    goarch:
      - arm64
    binary: start_server
    ldflags:
      - -s -w
      - -X github.com/shogo82148/server-starter.version={{.Version}}
      - -X github.com/shogo82148/server-starter.commit={{.ShortCommit}}
archives:
  - builds:
      - cli-amd64
      - cli-arm64
    name_template: "start_server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"

nfpms:
  - id: package-amd64
    builds:
      - cli-amd64
    package_name: go-server-starter
    homepage: https://github.com/shogo82148/server-starter/
    maintainer: Ichinose Shogo <shogo82148@gmail.com>
    description: Yet Another Go port of start_server by shogo82148
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    release: 1
    epoch: 0
    bindir: /usr/bin
  - id: package-arm64
    builds:
      - cli-arm64
    package_name: go-server-starter
    homepage: https://github.com/shogo82148/server-starter/
    maintainer: Ichinose Shogo <shogo82148@gmail.com>
    description: Yet Another Go port of start_server by shogo82148
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    release: 1
    epoch: 0
    bindir: /usr/bin

blobs:
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    folder: amazonlinux/2/x86_64/go-server-starter
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    folder: amazonlinux/2/aarch64/go-server-starter
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    folder: centos/7/x86_64/go-server-starter
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    folder: centos/7/aarch64/go-server-starter
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    folder: centos/8/x86_64/go-server-starter
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    folder: centos/8/aarch64/go-server-starter
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    folder: almalinux/8/x86_64/go-server-starter
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    folder: almalinux/8/aarch64/go-server-starter
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    folder: rockylinux/8/x86_64/go-server-starter
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    folder: rockylinux/8/aarch64/go-server-starter

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
