name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        go:
          - "1.27"
          - "1.26"

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go }}

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@53e33bb27be492a926eee378e8a5f7ff6618b061 # v1.43.1
        with:
          perl-version: "5.44"

      - name: Install Server::Starter
        run: |
          cpanm --notest Server::Starter

      - name: Test
        run: |
          go test -v -race -coverprofile=profile.cov ./...
        env:
          SERVER_STARTER_INTEROP_REQUIRED: 1

      - name: Send coverage
        uses: shogo82148/actions-goveralls@77a1912dca42260ee3e97f61bd13ea7ef40baa93 # v1.11.2
        with:
          path-to-profile: profile.cov
          flag-name: Go-${{ matrix.go }}-${{ matrix.os }}
          parallel: true

  listener:
    name: Test of the listener package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        go:
          - "1.27"
          - "1.26"
          - "1.25"
          - "1.24"
          - "1.23"

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Test
        run: |
          go test -v -race -coverprofile=profile.cov ./...
        working-directory: listener

      - name: Send coverage
        uses: shogo82148/actions-goveralls@77a1912dca42260ee3e97f61bd13ea7ef40baa93 # v1.11.2
        with:
          path-to-profile: listener/profile.cov
          flag-name: Go-listener-${{ matrix.go }}-${{ matrix.os }}
          parallel: true

  # notifies that all test jobs are finished.
  finish:
    needs:
      - test
      - listener
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@77a1912dca42260ee3e97f61bd13ea7ef40baa93 # v1.11.2
        with:
          parallel-finished: true

  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: Check GoReleaser configure
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: "~> v2"
          args: check
